### ISSUE TITLE
weird apostrophe '

### ISSUE THREAD

**Issue by Faz95210** [PascalPixel/pokemon-font#4]
Hi,
I've been playing around with your font and its ligatures on intellij and I notice a weir behavior with the apostrophe around some [letters.](https://user-images.githubusercontent.com/6436351/39661622-2cc23006-5087-11e8-86f1-c06da9683f6b.png)

Otherwise it looks nice 👍

**Comment by kcalvinalvin** [comment]
Turn off your ligatures and it'll be fine :)

**Comment by PascalPixel** [comment]
These are indeed the ligatures included in the original font. `ʼk` is bizarre...
