### ISSUE TITLE
Webpage broken on firefox

### ISSUE THREAD

**Issue by merwok** [PascalPixel/pokemon-font#6]
Hello!  I wanted to visit https://superpencil.com/work/pokemon-font to install the font but with Firefox a 404 error page is displayed.

**Comment by simonewebdesign** [comment]
It looks fine for me on Firefox 79 (macOS 10.14.6)

**Comment by PascalPixel** [comment]
Thanks for the report, must have been down, works now!

**Comment by merwok** [comment]
Still doesn’t work 🙁
